import os
import time
from typing import Any

import streamlit as st
from dotenv import find_dotenv, load_dotenv
from transformers import pipeline
from huggingface_hub import InferenceClient
from google import genai

from utils.custom import css_code


load_dotenv(find_dotenv())

HUGGINGFACE_API_TOKEN = os.getenv("HUGGINGFACE_API_TOKEN")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

gemini_client = genai.Client(api_key=GEMINI_API_KEY)


def progress_bar(amount_of_time: int) -> Any:
    """
    A very simple progress bar that increases over time,
    then disappears when it reaches completion.
    :param amount_of_time: time taken
    :return: None
    """
    progress_text = "Please wait, Generative models hard at work"
    my_bar = st.progress(0, text=progress_text)

    for percent_complete in range(amount_of_time):
        time.sleep(0.04)
        my_bar.progress(percent_complete + 1, text=progress_text)

    time.sleep(1)
    my_bar.empty()


def generate_text_from_image(url: str) -> str:
    image_to_text: Any = pipeline(
        "image-text-to-text",
        model="Salesforce/blip-image-captioning-base"
    )

    result = image_to_text(
        url,
        text="A photo of",
        max_new_tokens=50,
        return_full_text=False
    )

    generated_text: str = result[0]["generated_text"]

    print(f"IMAGE INPUT: {url}")
    print(f"GENERATED TEXT OUTPUT: {generated_text}")

    return generated_text


def generate_story_from_text(scenario: str) -> str:
    """
    A function using Gemini to generate a short story.
    :param scenario: generated text from the image
    :return: generated story from the text
    """
    prompt = f"""
    You are a talented story teller who can create a story from a simple narrative.
    Create a story using the following scenario; the story should have a maximum of 50 words.

    CONTEXT: {scenario}

    STORY:
    """

    response = gemini_client.models.generate_content(
        model="gemini-3.5-flash-lite",
        contents=prompt
    )

    generated_story: str = response.text

    print(f"TEXT INPUT: {scenario}")
    print(f"GENERATED STORY OUTPUT: {generated_story}")

    return generated_story


def generate_speech_from_text(message: str) -> Any:
    """
    A function using the Kokoro text-to-speech model through
    Hugging Face Inference Providers.
    :param message: short story generated by the Gemini model
    :return: generated audio
    """
    client = InferenceClient(
        provider="deepinfra",
        api_key=HUGGINGFACE_API_TOKEN
    )

    audio = client.text_to_speech(
        message,
        model="hexgrad/Kokoro-82M"
    )

    with open("generated_audio.wav", "wb") as file:
        file.write(audio)


def main() -> None:
    """
    Main function.
    :return: None
    """
    st.set_page_config(
    page_title="VisionTale AI",
    page_icon="🖼️"
    )

    st.markdown(css_code, unsafe_allow_html=True)

    with st.sidebar:
        st.image("img/my_logo.png", width=180)
        st.write("---")
        st.write("Built by Mohammed Sumayya")

    st.title("🖼️ VisionTale AI")
    st.caption("Turn images into stories and speech.")

    uploaded_file: Any = st.file_uploader(
    "Upload an image to begin",
    type=["jpg", "jpeg", "png", "webp"]
    )

    if uploaded_file is not None:
        print(uploaded_file)

        bytes_data: Any = uploaded_file.getvalue()

        with open(uploaded_file.name, "wb") as file:
            file.write(bytes_data)

        st.image(
            uploaded_file,
            caption="Uploaded Image",
            width="stretch"
        )

        progress_bar(100)

        scenario: str = generate_text_from_image(uploaded_file.name)

        story: str = generate_story_from_text(scenario)

        generate_speech_from_text(story)

        with st.expander("Generated Image scenario"):
            st.write(scenario)

        with st.expander("Generated short story"):
            st.write(story)

        st.audio("generated_audio.wav")


if __name__ == "__main__":
    main()